# Generated by Django 6.0.4 on 2026-05-14 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar_url', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('substance', models.CharField(blank=True, choices=[('COCAINE', 'Cocaine'), ('CATHINONES', '3mmc / 4mmc'), ('AMPHETAMINE', 'Amphetamine / speed'), ('MDMA', 'MDMA / Ecstacy')], max_length=20)),
                ('usage_duration', models.CharField(blank=True, choices=[('<6M', 'Less than 6 months'), ('6-12M', '6 to 12 months'), ('1-2Y', '1 to 2 years'), ('>2Y', '2+ years')], max_length=10)),
                ('goal', models.CharField(blank=True, choices=[('USE_LESS', 'I want to use less'), ('QUIT', 'I want to quit completely'), ('NOT_SURE', "I'm not sure yet")], max_length=20)),
                ('usage_times', models.CharField(blank=True, choices=[('AT_A_PARTY', "When i'm at a party"), ('WHEN_BORED', "When i'm bored"), ('WHEN_STRESSED', "When i'm stressed or anxious"), ('WHEN_DOWN', "When i'm feeling down")], max_length=20)),
                ('frequency', models.CharField(blank=True, choices=[('RARELY', 'Rarely'), ('MONTHLY', 'At least once a month'), ('WEEKLY', 'At least once a week'), ('DAILY', 'Every day')], max_length=20)),
                ('previous_attempts', models.CharField(blank=True, choices=[('WENT_WELL', 'Yes, and it went better than I expected.'), ('ONCE_HARD', 'Yes, once. But it was hard to keep up'), ('MULTIPLE_RELAPSED', 'Yes, multiple times. But I keep falling back.'), ('THOUGHT_ABOUT_IT', "I've thought about it but haven't tried yet"), ('NEVER', 'No, this is the first time')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
    ]
