# Generated by Django 6.0.4 on 2026-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usage_duration',
            field=models.CharField(blank=True, choices=[('<6M', 'Less than 6 months'), ('6-12M', '6 to 12 months'), ('1-2Y', '1 to 2 years'), ('>2Y', '2+ years'), ('NOT_SURE', "I'm not sure")], max_length=20),
        ),
    ]
