# Generated by Django 6.0.4 on 2026-05-24 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_usage_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('param_key', models.CharField(max_length=50)),
                ('param_value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'avatar_item',
                'unique_together': {('param_key', 'param_value')},
            },
        ),
        migrations.CreateModel(
            name='UserAvatarItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_equipped', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to='user.avataritem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_avatar_item',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
