# Generated by Django 6.0.4 on 2026-06-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_avataritem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
    ]
