# Generated by Django 6.0.4 on 2026-05-14 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BubblePopContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_text', models.TextField()),
                ('thoughts', models.JSONField()),
            ],
            options={
                'db_table': 'bubble_pop_content',
            },
        ),
        migrations.CreateModel(
            name='ChoiceStoryContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_text', models.TextField()),
                ('story_content', models.JSONField()),
            ],
            options={
                'db_table': 'choice_story_content',
            },
        ),
        migrations.CreateModel(
            name='JournalContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_text', models.TextField()),
            ],
            options={
                'db_table': 'journal_content',
            },
        ),
        migrations.CreateModel(
            name='LetterContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_text', models.TextField()),
            ],
            options={
                'db_table': 'letter_content',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'phase',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScaleContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_text', models.TextField()),
                ('left_label', models.TextField()),
                ('right_label', models.TextField()),
            ],
            options={
                'db_table': 'scale_content',
            },
        ),
        migrations.CreateModel(
            name='SpeechBubbleContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_text', models.TextField()),
                ('bubbles', models.JSONField()),
            ],
            options={
                'db_table': 'speech_bubble_content',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journey',
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('banner_url', models.TextField()),
                ('assignment_type', models.TextField()),
                ('is_core', models.BooleanField(default=False)),
                ('activation_rules', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bubble_pop_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_step', to='journey.bubblepopcontent')),
                ('choice_story_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_step', to='journey.choicestorycontent')),
                ('journal_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_step', to='journey.journalcontent')),
                ('letter_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_step', to='journey.lettercontent')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='journey.phase')),
                ('scale_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_step', to='journey.scalecontent')),
                ('speech_bubble_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_step', to='journey.speechbubblecontent')),
            ],
            options={
                'db_table': 'journey_step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStepProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UNAVAILABLE', 'Unavailable'), ('AVAILABLE', 'Available'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='AVAILABLE', max_length=20)),
                ('bookmarked', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progresses', to='journey.journey')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='journey.journeystep')),
            ],
            options={
                'db_table': 'journey_step_progress',
            },
        ),
    ]
