# Generated by Django 6.0.4 on 2026-05-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='assignment_type',
            field=models.CharField(choices=[('journal', 'Journal'), ('letter', 'Letter'), ('choice_story', 'Choice Story'), ('speech_bubble', 'Speech Bubble'), ('bubble_pop', 'Bubble Pop'), ('scale', 'Scale')], max_length=20),
        ),
    ]
