# Generated by Django 6.0.4 on 2026-06-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_assignment_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcontent',
            name='input_field_placeholder',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lettercontent',
            name='greeting_placeholder',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
